apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appNameTwo }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app: {{ .Values.appNameTwo }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  strategy:
    type: {{ .Values.strategy.type }}
    rollingUpdate:
      maxSurge: {{ .Values.strategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.strategy.rollingUpdate.maxUnavailable }}
  selector:
    matchLabels:
      app: {{ .Values.appNameTwo }}
  template:
    metadata:
      labels:
        app: {{ .Values.appNameTwo }}
        # Including the tag here guarantees a new RS when the tag changes
        app.kubernetes.io/version: "{{ .Values.image.tag }}"
    spec:
      containers:
        - name: {{ .Values.appNameTwo }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessPath }}
              port: 80
            initialDelaySeconds: 2
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessPath }}
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
