apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gitops-overrides-test.fullname" . }}-snapshot
data:
  replicaCount: {{ .Values.replicaCount | toString | quote }}
  image.repository: {{ .Values.image.repository | toString | quote }}
  image.tag: {{ .Values.image.tag | toString | quote }}
  testEnv.yaml: |
{{ toYaml .Values.testEnv | indent 4 }}
