apiVersion: v1
kind: Secret
metadata:
  name: gitops-secret-account-text
  namespace: ivan-test
  labels:
    app: gitops-secret-test
type: Opaque
stringData:
  value: <+secrets.getValue("account.test-secret-acc")>

---
apiVersion: v1
kind: Secret
metadata:
  name: gitops-secret-account-file
  namespace: ivan-test
  labels:
    app: gitops-secret-test
type: Opaque
stringData:
  # Will contain FILE secret contents as plain text after rendering
  value: <+secrets.getValue("account.test-secret-acc-file")>

---
apiVersion: v1
kind: Secret
metadata:
  name: gitops-secret-org-text
  namespace: ivan-test
  labels:
    app: gitops-secret-test
type: Opaque
stringData:
  value: <+secrets.getValue("org.test_secret_org_lvl")>

---
apiVersion: v1
kind: Secret
metadata:
  name: gitops-secret-org-file
  namespace: ivan-test
  labels:
    app: gitops-secret-test
type: Opaque
stringData:
  value: <+secrets.getValue("org.text_secret_org_lvl_file")>

---
apiVersion: v1
kind: Secret
metadata:
  name: gitops-secret-project-text
  namespace: ivan-test
  labels:
    app: gitops-secret-test
type: Opaque
stringData:
  value: <+secrets.getValue("text_secret_proj_lvl")>

---
apiVersion: v1
kind: Secret
metadata:
  name: gitops-secret-project-file
  namespace: ivan-test
  labels:
    app: gitops-secret-test
type: Opaque
stringData:
  value: <+secrets.getValue("text_secret_proj_lvl_file")>
