apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-app-chart-single-artifact
  labels:
    app: helm-app-chart-single-artifact
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: helm-app-chart-single-artifact
  template:
    metadata:
      labels:
        app: helm-app-chart-single-artifact
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
